// Server Component layout (no client directive)

import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";

import { TRPCReactProvider } from "~/trpc/react";
import { auth, signOut } from "~/server/auth";
// Removed desktop Sidebar; using hamburger/mobile menu only
import { MobileMenu } from "~/components/ui/mobile-menu";
import { Toaster } from "~/components/ui/toaster";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

async function doSignOut() {
  "use server";
  await signOut({ redirectTo: "/sign-in" });
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-neutral-950 text-white">
        <MobileMenu isAuthenticated={!!session?.user} onSignOut={doSignOut} />
        <main className="flex-1">
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </main>
        <Toaster richColors position="top-right" theme="dark" />
      </body>
    </html>
  );
}
