"use client";

import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";

import { TRPCReactProvider } from "~/trpc/react";
import { auth, signOut } from "~/server/auth";
import { Button } from "~/components/ui/button";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

async function doSignOut() {
  // "use server";
  await signOut({ redirectTo: "/sign-in" });
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-neutral-950 text-white">
        <header className="flex items-center justify-between border-b border-white/10 px-4 py-2">
          <Link href="/" className="cursor-pointer text-sm font-semibold">
            ShellGate
          </Link>
          <div>
            {session?.user ? (
              <form action={doSignOut}>
                <Button type="submit" variant="outline">
                  Sign Out
                </Button>
              </form>
            ) : null}
          </div>
        </header>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
